Maude Alpha110b

diff --git a/tests/Misc/smtTest b/tests/Misc/smtTest
--- a/tests/Misc/smtTest
+++ b/tests/Misc/smtTest
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+if grep "#define USE_CVC4" ../../config.h ; # are we using CVC4?
+then
+  echo "testing CVC4"
+else
+  echo "no CVC4"
+  exit 77 # grep returned nonzero exit so skip this test
+fi
+
 MAUDE_LIB=$srcdir/../../src/Main
 export MAUDE_LIB
 
